/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.5.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addNote from "../addNote";
import type * as common from "../common";
import type * as createAdmin from "../createAdmin";
import type * as createApplication from "../createApplication";
import type * as deleteSubmission from "../deleteSubmission";
import type * as getAllSubmissions from "../getAllSubmissions";
import type * as getApplication from "../getApplication";
import type * as getNotes from "../getNotes";
import type * as getSubmission from "../getSubmission";
import type * as storeUser from "../storeUser";
import type * as updateSubmission from "../updateSubmission";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addNote: typeof addNote;
  common: typeof common;
  createAdmin: typeof createAdmin;
  createApplication: typeof createApplication;
  deleteSubmission: typeof deleteSubmission;
  getAllSubmissions: typeof getAllSubmissions;
  getApplication: typeof getApplication;
  getNotes: typeof getNotes;
  getSubmission: typeof getSubmission;
  storeUser: typeof storeUser;
  updateSubmission: typeof updateSubmission;
}>;
