/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.5.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as autoSaveData from "../autoSaveData";
import type * as createApplication from "../createApplication";
import type * as createUser from "../createUser";
import type * as getAllSubmissions from "../getAllSubmissions";
import type * as getApplication from "../getApplication";
import type * as getAutoSaveData from "../getAutoSaveData";
import type * as getSubmission from "../getSubmission";
import type * as storeUser from "../storeUser";
import type * as updateSubmission from "../updateSubmission";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  autoSaveData: typeof autoSaveData;
  createApplication: typeof createApplication;
  createUser: typeof createUser;
  getAllSubmissions: typeof getAllSubmissions;
  getApplication: typeof getApplication;
  getAutoSaveData: typeof getAutoSaveData;
  getSubmission: typeof getSubmission;
  storeUser: typeof storeUser;
  updateSubmission: typeof updateSubmission;
}>;
